### ISSUE TITLE
Team Check-in

### ISSUE THREAD

**Issue by MJholland** [paprika-spice/web-app#16]

**Comment by TeriDibbits** [comment]
This past week my goal was to get ready for the pitch next week. My tasks consisted of organizing our research in the google doc so it is set up and ready to go for the milestone. This included learning up images of our sketches and making sure every section of the milestone was covered. I was in charge of completing the room screen for the prototype. I had some difficulty understanding the purpose of a feature of our prototype. Trying to gain clarity over slack wasn't effective because communication over slack can be confusing and much easier to discuss in person. Finally I created an invision board to represent the style and design of our app.

**Comment by MJholland** [comment]
This week my tasks were to research fonts for our Invision board and Logo, create a logo and create the first three screens of our XD prototype. As a team, we discussed what we wanted to achieve with fonts, something simple like a system font without being a system font. Using this I picked a pairing font for our logo so we could have something with a little more flair to go along with our app font. A challenge while creating the app screens was working with sketches I didn't create as I wasn't 100% sure what I was looking at but with quick responses from team members, I was put back on track.

**Comment by scallsen** [comment]
This weeks goal was to set up the interactive wireframe in Adobe XD, as well as research different options for coding our web app. For the wireframe, I founds it was most useful to delegate each member with certain parts of the wireframe, and have them complete their part and pass the file on to the next person. I would like to know more about how this is achieved in the real world on larger teams, it would be interesting to know. For my research for coding solutions, with the timeframe that we have it may be easier to code the site from scratch and not make my team learn a new code framework.
