### ISSUE TITLE
Conduct Usability Testing

### ISSUE THREAD

**Issue by TeriDibbits** [paprika-spice/web-app#19]

**Comment by TeriDibbits** [comment]
**Project**: Workspace
**Facilitator**: Teri Dibbits
**User**: Student at Algonquin College

**Task #1**: Login and select a specific time and date you wish to book a room
Observations:
-Login was smooth and located without hesitation
-The user knew how to change the time and date, however, they didn't not realize the option to chose between flexible time and specific time
Feedback:
-Add a dash between times so it shows that it is from this time to this time
-Make the clock icon/ time options either more noticeable or look more like a button

**Task #2**: Select the building you wish to book a room in
Observations:
-Clicked on buildings and selected a building with ease
Feedback:
-The buildings button wasn't 100% clear it is a button. Questioned before selecting. It made sense to click it because there was no other option

**Task #3**: Select the features you wish to see in the room you are booking
Observations:
-Easily found features, due to previous task. Selected the features they wanted to in a room
Feedback:
-Mentioned picking features first and then offer buildings, however, I explained that these variable will determine the same results regardless of the feature that is selected first.

**Task #4**: Book a room
Observations:
-Slight hesitation before selecting a room card on the home screen
-Confusion before realizing they could scroll down and book the room
Feedback:
-The room booking confirmation page isn't very readable
-Adding a title above room options. (eg. Rooms available in N building) This would eliminate any confusion
-Don't give them the option to change the time and date on the room screen, because what if they change it to a time that is not available? Will a notice pop up to say that that time or date is not available?
-Consider showing the schedule calendar before the booking time on the room screen. Then outline the details at the bottom before the click the button. (This includes: Room, date, and time)
-The understand the where we are going with the flexible time, however, if you only give them the one option to chose a time there will be no overlap and they will just see what is available for that time. (Suggestion)
-Clarify that highlighted blue squares on calendar are the current booked times for that room. Perhaps put the word "Booked" on the blue square or a notice/ legend above the calendar.

**Comment by scallsen** [comment]
# Usability Testing Record
**Project**: Workspace
**Facilitator**: Simon Callsen
**Date**: Friday, February 09 2018
**Users**: Kelly Miles, Christina Muxlow, Katrin Emery
**Notes**: Testing was completed one after another, with overall comments and feedback given and recorded by myself.

### Task 1: Login and select a specific time and date you wish to book a room
- There was friction regarding Specific Time <--> Flexible Time
- Users were confused as to it's function
- It should be easier to view the current state

### Task 2: Select the building you wish to book a room in
- No comments noted here

### Task 3: Select the features you wish to see in the room you are booking
- May be beneficial to make the entire process a "step by step" process, and then allow for refinement
- Then the application should suggest the best choices that match the user's selection
- Flexible booking may make more sense that way

### Task 4: Book a room
- Difficult to press small icons [NOTE: Adobe XD Issue, make sure we add a larger clickable div around the icon for final web product]
- Users were slightly lost as they progressed through the app flow, having a "current step" always visible that informed them what step they were on may help "Selecting Room / Choosing Time / Confirming Selection .etc"
- It should be easy for a "old fashioned way" of searching rooms, i.e. pick desired room and select a time on the schedule, as some teams might need a specific room.
- Recommend similar rooms feature would be appreciated - using feature tags could be done

**Comment by MJholland** [comment]
Project: Workspace
Facilitator: MJ Holland
User: Grandmother

**Task #1: Login and select a specific time and date you wish to book a room**
Observations:
- Login went flawlessly
- Understood where to change the date but didn't understand when nothing happened
- Same as above for time, vaguely understood what would happen but needed a visual
- Accidentally selected variable time option while trying to select a time
- Understood how the variable option worked

Feedback:
- Would have been nice to see what the options did
- Use a drop-down for the variable time section similar to the others
- Reducing the blue space at the top would allow more room for bigger icons and extra drop-downs

**Task #2: Select the building you wish to book a room in**
Observations:
- Immediately tapped on one of the rooms on the list
- Didn't notice the back button right away
- Made it to the buildings list eventually 
- Was unsure if she needed to press back after or if it would go back a screen after selecting a building.

Feedback:
- Need to make it more obvious
- Suggested adding another title and use highlighting like inside the buildings screen

**Task #3: Select the features you wish to see in the room you are booking**
Observations:
- Got to feature easier after dealing with getting to buildings
- Understood how selecting features worked because of the last task

Feedback:
- Same stuff as the last task

**Task #4: Book a room**
Observations:
- She knew what to do as she accidentally did it before
- Wondered about changing options once on this screen
- Got a little confused at the number of blue boxes after selecting one time slot
- finished booking the room easily

Feedback:
- 6 day calendar was weird to her
- Increase text size on the calendar a little
- Need to add a colour to the calendar to show which slot is your own

**Overall Impression**
- Works well, some of it was confusing but with enough uses she could get used to it

**Comment by MJholland** [comment]
Clicking on the tasks with # infront lead to previous sprint tasks lol
