### ISSUE TITLE
Complete Web app rubric

### ISSUE THREAD

**Issue by TeriDibbits** [paprika-spice/web-app#78]

**Comment by scallsen** [comment]
## DATA & CODING COMPONENT

| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Accessibility** | No one can use the site | Only accessible to a handful of special people | Accessible to most people | Anyone in the world can use the site |
| **Responsiveness** | Not responsive | Responsive on some screens | Responsive but there is some issues | Website is responsive and looks great on all screen sizes |
| **Performance** | Doesn't load or loads super slow | Loads slowly | Good loading time, but could be faster | Excellent loading time |
| **Code Quality** | Coded by someone in Kindergarten | Code quality of a first year student | Coded like a second year, close to perfect but still lacking | Semantically correct and fully incorporates best practices |
| **Teamwork** | What team? | Some teamwork happened but it fell apart after a short time.  | Communication was something, work was performed ok together | Worked great together. Communicated often and made decisions together. Everyone took on the workload they were assigned. |

**Comment by scallsen** [comment]
## Data & Coding Component Scores

| Category | Desired Score | Reason |
| --- | --- | --- |
| **Accessibility** | 2 | All accessibility tests passed except: Contrast ratio low - caused by using Algonquin brand colours, the client would decide that. Our confirmation box is created using a page redirect, that should be avoided to not cause confusion to users with a screen reader. | 
| **Responsiveness** | 3 | Works on all screens and sizes. |
| **Performance** | 3 | Site loads fast on all browsers, essential imagery as SVG, limited raster image use. Score of 95/100 on Lighthouse. Home page loads in 2100 ms. |
| **Code Quality** | 2 | Correct indentation and coding practices applied. Form validation is not present, although would be implemented if the data was being sent somewhere. |
| **Teamwork** | 3 | Proper communications across our Slack channels, work divided and completed fairly. |
