### ISSUE TITLE
Team Check-in

### ISSUE THREAD

**Issue by scallsen** [paprika-spice/web-app#8]
Give the teacher a progress report of how your team and project is progressing.

Discuss team dynamics & member contributions
Discuss successes & failures
Ask questions & get help
Show project board & issues
Determine the plan for the next sprint

**Comment by scallsen** [comment]
Week 2 Wrapup
--

After looking through the data we obtained from our survey, it is clear that students on different campuses want a better solution for room booking.
Our team developed flow and potential screens to use, as well as functions that we want included in our final application. 

**Discuss team dynamics & member contributions**
Our team divided our work to complete and had everything done for class.

**Discuss successes & failures**
We did not have too many screens to discuss, although we had enough to move forwards.

**Comment by MJholland** [comment]
@thomasjbradley

**Comment by TeriDibbits** [comment]
This past week we learned how to use github to organize our tasks as a group. This new learning experience was challenging and a bit confusing, making me feel a bit behind. My group seemed to understand how it worked a bit better which helped, but I still wanted to be able to do my part. The workload for this week was a bit heavier because we didn't have class time to work on it the first week. Working as a team we were able to successfully complete all our of tasks for this weeks sprint.

**Comment by MJholland** [comment]
The past week I needed to create user personas, send out our survey and ideate potential app flows. I managed to get two of the three tasks completed. The one task I didn't finish was the app flows as I ran out of time with other things taking up most of my attention. The other members of the group seem to have a better vision of the app than I do but when we met in class I was still able to contribute ideas. Because of the two tasks I did get finished I feel like I have a thorough understanding of who our users are and can provide advice that will cater better to them.

**Comment by TeriDibbits** [comment]
Everyone completed their personal week review.

**Comment by thomasjbradley** [comment]
@TeriDibbits @scallsen 
Try to be a little more personal with the next reflections. You should be saying "I" instead of "We".

---

Sprint 2 looks okay, but the Issues could be a little more detailed. Also, close Sprint 2 now because its complete.
